force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <label>Meetup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <label>RegistrationCode</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/MeetupRegistration__c.object-meta.xml
<CustomObject>
    <label>MeetupRegistration</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MeetupRegistrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MeetupRegistration__c/fields/Meetup__c.field-meta.xml
<CustomField>
    <fullName>Meetup__c</fullName>
    <label>Meetup</label>
    <referenceTo>Meetup__c</referenceTo>
    <relationshipLabel>MeetupRegistrations</relationshipLabel>
    <relationshipName>MeetupRegistrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RegistrationController.cls
public with sharing class RegistrationController {
    
    @AuraEnabled
    public static boolean ValidateRegistration(String registrationCode) {
        List<Meetup__c> meetUp = [select id from Meetup__c where RegistrationCode__c=:registrationCode];
        if(meetUp != null && meetUp.size() > 0)
        {
            return true;
        }
        return false;
    }
    @AuraEnabled
    public static void SaveRegistration(String firstName, String lastName, String email, String registrationCode) {
        List<Meetup__c> meetUp = [select id from Meetup__c where RegistrationCode__c=:registrationCode];
        if(meetUp == null || meetUp.size() == 0)
        {
            CustomException ex = new CustomException();
            ex.setMessage('Invalid Registration code.');
            throw ex;
           
        }
        MeetupRegistration__c reg = new MeetupRegistration__c();
        reg.FirstName__c = firstName;
        reg.LastName__c = lastName;
        reg.Email__c = email;
        reg.Meetup__c = meetUp[0].Id;
        insert reg;
        
    }

    public class CustomException extends Exception  {}

}